from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Represents a single citation reference with source and chunk information.

    This model stores metadata about where a citation originated from, including
    the source document ID and the specific chunk ID within that source. The citation
    number corresponds to the [CITATION: N] markers embedded in the main text.

    Chunk content in the retrieval pipeline may be wrapped with internal IDs, for
    example: `<<<CHUNK_0>>>...chunk text...<<<CHUNK_0>>>`. These wrapper IDs are
    generated by the system and are not meant to be modified or invented by the
    model. The model only ever works with a numeric chunk index (0..N-1) via the
    `chunkId` field.
    """

    citation: str = Field(
        ...,
        description="The citation number as a string (e.g., '1', '2', '3'). This "
        "corresponds to the [CITATION: N] marker in the main text where this citation "
        "is referenced.",
    )
    sourceId: str = Field(
        ...,
        description="Unique identifier for the source document where this citation "
        "originated. Typically a UUID that references the original document or data "
        "source in the system.",
    )
    chunkId: int = Field(
        ...,
        ge=0,
        description=(
            "Zero-based index of the chunk within the current answer context.\n\n"
            "Each chunk is wrapped with numeric "
            "markers around its content:\n\n"
            "  <<<123>>>This is the child chunk text<<</123>>>\n\n"
            "The model must copy this numeric index exactly and MUST NOT invent "
            "new indices or IDs."
        ),
    )
    brief_summary: str = Field(
        ...,
        description="A concise summary of the citation content. This provides a "
        "brief overview of the key information or main point conveyed by the cited "
        "text, typically in one to two sentences. "
        r"CRITICAL: Do NOT use backslashes (\) or LaTeX syntax. Use plain text only.",
    )


class TextWithCitations(BaseModel):
    r"""Represents text content with embedded citations and their detailed references.

    This model is used to structure AI-generated responses that include citations.
    The main text contains [CITATION: N] markers that reference entries in the
    citations array, allowing for traceable and verifiable AI responses.

    IMPORTANT: All text fields must NOT contain backslashes (\) or LaTeX syntax.
    Use plain text or simple markdown formatting only.
    """

    text: str = Field(
        ...,
        description="The main text content with embedded citation markers in the "
        "format [CITATION: N] where N is the citation number. These markers indicate "
        "where in the text a citation should be referenced. "
        r"CRITICAL: Do NOT use backslashes (\) or LaTeX syntax. Use plain text or simple markdown only.",
    )
    citations: list[Citation] = Field(
        ...,
        description="List of citation objects that correspond to the [CITATION: N] "
        "markers in the text. Each citation provides the source text, source ID, "
        "chunk ID, and citation number for traceability.",
    )
